COMP: Limit traitlets to <5.7.0
To address #588:

> TraitError: label_image_weights shape expected to have 1 components, but got () components

We also have to explicitly install notebook, ipywidgets, because they
are not installed via dependencies, and set them to versions compatible
to traitslets 5.6.