BUG: app.builder can be None
To address:

```
Running Sphinx v5.0.2
making output directory... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/itkwidgets/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 275, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/itkwidgets/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 237, in __init__
    self.config.setup(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/itkwidgets/checkouts/latest/docs/conf.py", line 79, in setup
    if RTD and app.builder.format == "html":
AttributeError: 'NoneType' object has no attribute 'format'
```