BUG: rechunk roi data after slicing
So the roi image, when used later either in another view call or saving
with to_ngff_zarr, we do not run into the error:

```
ValueError: Attempt to save array to zarr with irregular chunking, please call `arr.rechunk(...)` first
```